<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container685CrfM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container685CrfM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container685CrfM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container685CrfM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container685CrfM\App_KernelDevDebugContainer([
    'container.build_hash' => '685CrfM',
    'container.build_id' => '0ffffece',
    'container.build_time' => 1647849436,
], __DIR__.\DIRECTORY_SEPARATOR.'Container685CrfM');
